language: csharp
mono: none
dist: bionic
dotnet: 3.0
addons:
  apt:
    packages:
    - libc6-dev
    - libgdiplus
script:
- dotnet build -c release
- ./render-all.sh 180
- ./deploy.sh
deploy:
  provider: pages
  local-dir: out
  github-token: $GITHUB_TOKEN
  on:
    branch: master
